### ISSUE TITLE
Missing README and proper documentation.

### ISSUE THREAD

**Issue by pixnbit** [emostar/flutter-libphonenumber#16] opened 2020-03-23 05:54 UTC
I appreciate your efforts in putting this together. At least provide some examples in the README  as a starting point?

**Comment by emostar** [comment] 2020-04-02 06:59
I totally agree with you. I created this to fix an immediate need on my part. Looks like it has been getting more usage these days, so I'll see about improving the project.

In the meantime, there is the example app that shows how to use it in code. Have you seen it at https://github.com/emostar/flutter-libphonenumber/blob/master/example/lib/main.dart?

**Comment by emostar** [comment] 2020-04-02 07:02
Duplicate of #1

**Closed by emostar** 2020-04-02 07:02 UTC
