### ISSUE TITLE
formatAsYouType is not working on Flutter Web

### ISSUE THREAD

**Issue by BradyEdgar94** [emostar/flutter-libphonenumber#14] opened 2020-03-11 21:10 UTC
I am trying to use the formatAsYouType method for a Flutter app and everything is working fine on mobile. However when I try to use it for the web the await does not seem to ever finish and just hangs up.

I have it inside an async function which looks like the following:

```
onSubmit: (Map<String, dynamic> phoneData) async {
          print("################______${phoneData['phone']}");
          final formattedNumber = await PhoneNumberUtil.formatAsYouType(
            phoneNumber: phoneData['phone'],
            isoCode: phoneData['countryCode'].code,
          );

          print("################______$formattedNumber");
}
```

When I run this function, the first print statement will work, however the second never get printed because the `formatAsYouType` method is just hanging up.

I then added it inside a try catch and the error I am getting is 
`MissingPluginException(No implementation found for method formatAsYouType on channel codeheadlabs.com/libphonenumber)`

**Comment by emostar** [comment] 2020-10-02 17:44
I'm going to close this as a duplicate of #22

**Closed by emostar** 2020-10-02 17:44 UTC
